### PR TITLE
Wrap apparmor calls with smbsafe

### LINKED ISSUE #542: Calls to apparmor should be wrapped with smbsafe
We missed this part when implementing the apparmor manager.

From the `smbsafe` documentation:
> libsmbclient overrides sigchild without setting SA_ONSTACK
It means that any cmd.Wait() would segfault when ran concurrently with this.

### PR DESCRIPTION
**Pull request by GabrielNagy**
This is a requirement for executed commands because `libsmbclient` overrides sigchild without setting `SA_ONSTACK`, so any `cmd.Wait()` would segfault when ran concurrently with this.

Closes #542 / DEENG-541

### CODE REVIEW

File: internal/policies/apparmor/apparmor.go [hunk 1]
```diff
@@ -229,6 +230,8 @@ func (m *Manager) applyMachinePolicy(ctx context.Context, e entry.Entry, apparmo
 		// #nosec G204 - We are in control of the arguments
 		cmd := exec.CommandContext(ctx, apparmorParserCmd[0], apparmorParserCmd[1:]...)
 		cmd.Dir = m.apparmorDir
+		smbsafe.WaitExec()
+		defer smbsafe.DoneExec()
```
Comment (didrocks) [inline internal/policies/apparmor/apparmor.go:234]: defer encompasses for now the `os.RemoveAll` wich may take some time. I think it’s better to release the lock as soon as possible.

Of course, think about doing it in the error case too :)
